"""Install double-clickable launchers for pip-installed users.

The bundled launcher templates live in `scrollback/launchers/`. For a
source checkout users could double-click them directly, but a
`pip install` user needs them copied somewhere reachable. This module
implements `scrollback install-launcher`:

* macOS  -> copies `scrollback.command` to ~/Desktop (or `--dest`), and
            optionally builds a real `scrollback.app` bundle.
* Linux  -> installs `scrollback.desktop` into the application menu, and
            copies `scrollback.sh` to ~/Desktop (or `--dest`).
* Windows-> copies `scrollback.bat` to the Desktop (or `--dest`).

It never overwrites without telling the user, and it prints exactly what
it created so there is no hidden state.
"""

from __future__ import annotations

import os
import shlex
import stat
import sys
from dataclasses import dataclass
from importlib import resources
from pathlib import Path

_PKG = "scrollback.launchers"


def _read_bundled(name: str) -> str:
    return resources.files(_PKG).joinpath(name).read_text(encoding="utf-8")


def _desktop_dir() -> Path:
    d = Path.home() / "Desktop"
    return d if d.is_dir() else Path.home()


def _make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _write(path: Path, content: str, *, executable: bool = False) -> None:
    path.write_text(content, encoding="utf-8")
    if executable:
        _make_executable(path)


def install(dest: Path | None = None, *, desktop: bool = False,
            app_bundle: bool = False) -> list[Path]:
    """Install the OS-appropriate launcher(s). Returns the paths created.

    The two selectors choose *which* artifacts to create:

    - ``desktop``    -- the Desktop launcher (macOS ``.command`` / Windows
      ``.bat`` / Linux ``.desktop`` + ``.sh``).
    - ``app_bundle`` -- a double-clickable ``.app`` (macOS only).

    If **neither** is requested, both are created (the "give me everything"
    default). On platforms without an ``.app``, ``app_bundle`` falls back to
    the Desktop launcher, so the flag never errors.
    """
    want_desktop = desktop or not (desktop or app_bundle)
    want_app = app_bundle or not (desktop or app_bundle)

    created: list[Path] = []
    if sys.platform == "darwin":
        created += _install_macos(dest, desktop=want_desktop, app_bundle=want_app)
    elif sys.platform == "win32":
        # No .app on Windows; any selection maps to the Desktop launcher.
        created += _install_windows(dest)
    else:
        created += _install_linux(dest)
    return created


def _install_macos(dest: Path | None, *, desktop: bool, app_bundle: bool) -> list[Path]:
    created: list[Path] = []
    if desktop:
        target_dir = dest or _desktop_dir()
        target_dir.mkdir(parents=True, exist_ok=True)
        cmd = target_dir / "scrollback.command"
        # Generate with the interpreter path baked in (Finder/GUI launches run
        # with a minimal PATH that excludes conda/venv bins).
        _write(cmd, _command_script(), executable=True)
        created.append(cmd)
    if app_bundle:
        created.append(_build_macos_app(dest))
    return created


def _command_script() -> str:
    """A .command launcher that opens a Terminal window and shows status."""
    # shlex.quote so an interpreter path with spaces/quotes/$ is shell-safe.
    py = shlex.quote(sys.executable or "python3")
    return (
        "#!/bin/bash\n"
        "# Generated by `scrollback install-launcher`. Double-click to run.\n"
        f"PY={py}\n"
        'if [ ! -x "$PY" ]; then PY="$(command -v python3 || command -v python)"; fi\n'
        'echo "Starting scrollback  (close the app window to stop)"\n'
        # --app: native window if pywebview is present (no lingering terminal);
        # otherwise it falls back to a browser window that auto-stops the
        # server when closed.
        'exec "$PY" -m scrollback.cli web --app\n'
    )


def _runner_script() -> str:
    """A self-contained launch script with the interpreter path baked in.

    Uses the absolute path of the Python that is running `install-launcher`
    (which, by construction, has scrollback installed). This survives the
    minimal PATH that macOS/GUI launchers run with. Errors are logged to
    ~/Library/Logs so a silent failure can be diagnosed.
    """
    # The script is intentionally dumb: it only locates the interpreter and
    # delegates everything (including how to open a window) to Python, which
    # owns all platform-specific logic. `--app` opens a native window when
    # pywebview is available (no terminal; closing it stops the server), and
    # otherwise falls back to a browser window with heartbeat auto-shutdown.
    py = shlex.quote(sys.executable or "python3")
    return (
        "#!/bin/bash\n"
        "# Generated by `scrollback install-launcher`.\n"
        f"PY={py}\n"
        'LOG="$HOME/Library/Logs/scrollback-launcher.log"\n'
        'mkdir -p "$(dirname "$LOG")" 2>/dev/null\n'
        'if [ ! -x "$PY" ]; then PY="$(command -v python3 || command -v python)"; fi\n'
        'exec "$PY" -m scrollback.cli web --app >> "$LOG" 2>&1\n'
    )


def _build_macos_app(dest: Path | None) -> Path:
    """Create a minimal double-clickable scrollback.app bundle."""
    base = dest or (Path.home() / "Applications")
    base.mkdir(parents=True, exist_ok=True)
    app = base / "scrollback.app"
    macos = app / "Contents" / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)

    # Launcher script inside the bundle. macOS launches .app bundles with a
    # minimal PATH that excludes conda/venv bins, so we bake the ABSOLUTE
    # interpreter path (known at install time) instead of relying on PATH.
    runner = macos / "scrollback"
    _write(runner, _runner_script(), executable=True)

    from . import __version__

    # Copy the bundled .icns into Contents/Resources so Finder/Dock show it.
    icon_line = ""
    try:
        icns = resources.files("scrollback.assets").joinpath("icon.icns").read_bytes()
        resources_dir = app / "Contents" / "Resources"
        resources_dir.mkdir(parents=True, exist_ok=True)
        (resources_dir / "scrollback.icns").write_bytes(icns)
        icon_line = "  <key>CFBundleIconFile</key><string>scrollback</string>\n"
    except (OSError, ModuleNotFoundError, FileNotFoundError):
        pass  # icon is optional; bundle still works without it

    info = app / "Contents" / "Info.plist"
    info.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0"><dict>\n'
        "  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>\n"
        "  <key>CFBundleName</key><string>scrollback</string>\n"
        "  <key>CFBundleDisplayName</key><string>scrollback</string>\n"
        "  <key>CFBundleIdentifier</key><string>dev.scrollback.app</string>\n"
        f"  <key>CFBundleVersion</key><string>{__version__}</string>\n"
        f"  <key>CFBundleShortVersionString</key><string>{__version__}</string>\n"
        "  <key>CFBundlePackageType</key><string>APPL</string>\n"
        "  <key>CFBundleExecutable</key><string>scrollback</string>\n"
        + icon_line
        + "  <key>LSUIElement</key><false/>\n"
        "</dict></plist>\n",
        encoding="utf-8",
    )
    return app


def _install_windows(dest: Path | None) -> list[Path]:
    target_dir = dest or _desktop_dir()
    target_dir.mkdir(parents=True, exist_ok=True)
    bat = target_dir / "scrollback.bat"
    _write(bat, _read_bundled("scrollback.bat"))
    return [bat]


def _install_linux(dest: Path | None) -> list[Path]:
    created: list[Path] = []
    # 1) application-menu entry
    apps_dir = (
        dest
        if dest
        else Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
        / "applications"
    )
    apps_dir.mkdir(parents=True, exist_ok=True)
    desktop = apps_dir / "scrollback.desktop"
    _write(desktop, _read_bundled("scrollback.desktop"), executable=True)
    created.append(desktop)
    # 2) a double-clickable copy on the Desktop
    sh = _desktop_dir() / "scrollback.sh"
    _write(sh, _read_bundled("scrollback.sh"), executable=True)
    created.append(sh)
    return created


# -- uninstall: locate + remove the artifacts install creates --------------

def installed_artifacts() -> list[Path]:
    """Return the launcher/app/log paths scrollback may have created.

    Covers the default install locations on every platform (a custom
    ``--dest`` is not tracked, so those must be removed by hand). Only paths
    that currently exist are returned. Never includes the user's agent data.
    """
    home = Path.home()
    candidates: list[Path] = []

    if sys.platform == "darwin":
        candidates += [
            _desktop_dir() / "scrollback.command",
            home / "Applications" / "scrollback.app",
            home / "Library" / "Logs" / "scrollback-launcher.log",
        ]
    elif sys.platform == "win32":
        candidates += [_desktop_dir() / "scrollback.bat"]
    else:
        apps = Path(os.environ.get("XDG_DATA_HOME", home / ".local" / "share")) / "applications"
        candidates += [
            apps / "scrollback.desktop",
            _desktop_dir() / "scrollback.sh",
        ]

    return [p for p in candidates if p.exists()]


def remove_path(path: Path) -> None:
    """Delete a file or directory (used to remove a .app bundle)."""
    import shutil

    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink()


# -- unified on-disk footprint --------------------------------------------

@dataclass(frozen=True)
class FootprintEntry:
    """One thing scrollback created on disk, tagged by tier.

    tier:
      * ``disposable`` -- derived/cache; safe to delete, rebuilt on demand
        (search index, browser profile). Removed by `uninstall`.
      * ``artifact``   -- things `install-launcher` created (Desktop launcher,
        .app bundle, launcher log, Linux .desktop). Removed by `uninstall`.
      * ``durable``    -- user-owned data (the archive vault). KEPT by
        `uninstall` unless `--purge-archive`.
    """

    path: Path
    tier: str
    description: str


def _dir_size(path: Path) -> int:
    total = 0
    if path.is_file():
        try:
            return path.stat().st_size
        except OSError:
            return 0
    for p in path.rglob("*"):
        if p.is_file():
            try:
                total += p.stat().st_size
            except OSError:
                pass
    return total


def footprint() -> list[FootprintEntry]:
    """Every path scrollback may have created on this machine, tagged by tier.

    The single source of truth consumed by `doctor` (visibility) and
    `uninstall` (what to remove). Only existing paths are returned. NEVER
    includes the user's agent data (opencode / Claude Code / ...), which
    scrollback only ever reads.
    """
    from . import fts

    entries: list[FootprintEntry] = []

    # disposable: search index + browser profile, and the cache dir that holds
    # them. The index path may be relocated via $SCROLLBACK_INDEX; the browser
    # profile lives under the standard cache dir.
    index = fts.default_index_path()
    if index.exists():
        entries.append(FootprintEntry(index, "disposable", "search index (rebuilt on demand)"))
    cache_dir = Path.home() / ".cache" / "scrollback"
    browser = cache_dir / "browser"
    if browser.exists():
        entries.append(FootprintEntry(browser, "disposable", "web-app browser profile"))
    # The cache parent, listed last so it is removed after its contents. Only
    # when it is the standard dir (a relocated index lives elsewhere).
    if cache_dir.exists():
        entries.append(FootprintEntry(cache_dir, "disposable", "cache directory"))

    # artifacts: launchers / app / log (existing enumeration)
    for p in installed_artifacts():
        entries.append(FootprintEntry(p, "artifact", "launcher / app / log"))

    # durable: the archive vault
    from . import archive

    vault = archive.default_archive_path()
    if vault.exists():
        entries.append(FootprintEntry(vault, "durable", "durable archive vault (your kept sessions)"))

    return entries
